### ISSUE TITLE
Carousel-Slider erhalten gleiche ID

### ISSUE THREAD

**Issue by chriza** [markocupic/bootstrap-carousel-bundle#1]
Contao 4.9.3
php 73

Hallo,
werden mehrere Carousel-Slider in einem Artikel erstellt, erhalten alle die ID des ersten Sliders: bootstrap-carousel-xx.

**Comment by markocupic** [comment]
Fixed in version 1.0.1 c38f4d3bd2026a57a1b11cfd1941bbfb3346d01a

**Comment by chriza** [comment]
Hallo,
die Anzahl der Indicatoren ist noch falsch. In den Slidern werden n-1 Indikatoren der folgenden Slider zusätzlich angezeigt.

**Comment by markocupic** [comment]
fixed in af4204eb602ebe50cdd48d1377cfdd22c91093b2
@chriza Try version 1.0.2
